POST http://localhost:3002/gestor/register/responsable Content-Type: application/json

// el gestor asigna un responsable

{
    "name":"helder",
    "email":"helder@empresa1.com",
    "passwordHash":"marc1234",
    "rolUser":"responsable",
    "carrec":"becario de recursos humanos",
    "telefon":"8932793",
    "nameEmpresa":"Empresa 1"
}