POST http://localhost:3002/borsa/registerOferta Content-Type: application/json

{
  "title" : "administrador "
  ,"description" : "dadsdasdasdas"
  ,"requirements" : "dasdadasdsddsa"
  , "skills" : "dasdasdad"
  , "ciclo" : "DAW"
  , "dateOfPublication" : 30032022
  , "expirationDate" : 30062022,
  "createBy" : "6363ba0963e0d22564251403",
   "refUsersInscritos": ["6363809909d5a3cca8990952","63808be33a6c3807bbf9c7b5","639c1ef68ffb9da450232d29"] 
}